[package]
name = "hyle-uuid-tld"
description = "Hyli Smart Contract"
license-file = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "uuid-tld"
path = "src/main.rs"
required-features = ["risc0"]
test = false

[dependencies]
sdk = { workspace = true }
borsh = { workspace = true }

risc0-zkvm = { workspace = true, optional = true, features = ['std'] }
client-sdk = { workspace = true, features = ["risc0"], optional = true }
uuid = { workspace = true }
rand = { version = "0.9" }
rand_seeder = { workspace = true }

[dev-dependencies]
risc0-zkvm = { workspace = true, features = ['std', 'prove'] }

[features]
default = []
client = ["dep:client-sdk"]
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
