[package]
name = "hyle-staking"
description = "Hyli Smart Contract"
license-file = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "staking"
path = "src/main.rs"
required-features = ["risc0"]
test = false

[dependencies]
sdk = { workspace = true, features = ["full-model"] }
hyllar = { workspace = true }
serde = { workspace = true, features = ["derive", "alloc"] }
anyhow = { workspace = true }
sha2 = { workspace = true }
borsh = { workspace = true, features = ["derive"] }

risc0-zkvm = { workspace = true, optional = true, features = ['std'] }
client-sdk = { workspace = true, features = ["risc0"], optional = true }

[dev-dependencies]
risc0-zkvm = { workspace = true, features = ['std', 'prove'] }

[features]
default = []
client = ["dep:client-sdk"]
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
