ARG DEP_IMAGE=rust:bookworm

FROM ${DEP_IMAGE} AS builder

WORKDIR /usr/src/hyli

COPY Cargo.toml Cargo.lock ./
COPY .cargo/config.toml .cargo/config.toml
COPY src ./src
COPY crates ./crates
RUN cargo build --release -p hyli-risc0-verifier-worker

FROM scratch
COPY --from=builder /usr/src/hyli/target/release/hyli-risc0-verifier /hyli-risc0-verifier
