services:
  hyli1:
    build: ./..
    privileged: true
    network_mode: host
    environment:
      - HYLI_ID=leader-1
      - HYLI_REST_ADDRESS=localhost:4001
      - HYLI_P2P__ADDRESS=localhost:1001
      - HYLI_DA_ADDRESS=localhost:4141
      - HYLI_TCP_ADDRESS=localhost:1414
      - RUST_LOG=debug
      - HYLI_CONSENSUS__SLOT_DURATION=3000
  hyli2:
    build: ./..
    privileged: true
    environment:
      - HYLI_ID=hyli2
      - HYLI_P2P__PEERS=localhost:1001
      - HYLI_REST_ADDRESS=localhost:4002
      - HYLI_P2P__ADDRESS=localhost:1002
      - HYLI_DA_ADDRESS=localhost:4142
      - HYLI_TCP_ADDRESS=localhost:2414
      - RUST_LOG=debug
      - HYLI_CONSENSUS__SLOT_DURATION=3000
    network_mode: host
    depends_on:
      - hyli1
  hyli3:
    build: ./..
    privileged: true
    environment:
      - HYLI_ID=hyli3
      - HYLI_P2P__PEERS=localhost:1001,localhost:1002
      - HYLI_REST_ADDRESS=localhost:4003
      - HYLI_P2P__ADDRESS=localhost:1003
      - RUST_LOG=debug
      - HYLI_DA_ADDRESS=localhost:4143
      - HYLI_TCP_ADDRESS=localhost:3414
      - HYLI_CONSENSUS__SLOT_DURATION=3000
    network_mode: host
    depends_on:
      - hyli1
  hyli4:
    build: ./..
    privileged: true
    environment:
      - HYLI_ID=hyli4
      - HYLI_P2P__PEERS=localhost:1001,localhost:1002,localhost:1003
      - HYLI_REST_ADDRESS=localhost:4004
      - HYLI_P2P__ADDRESS=localhost:1004
      - RUST_LOG=debug
      - HYLI_DA_ADDRESS=localhost:4144
      - HYLI_CONSENSUS__SLOT_DURATION=3000
    network_mode: host
    depends_on:
      - hyli1

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090" # Port pour accéder à l'interface de Prometheus
    network_mode: host
    depends_on:
      - hyli1
      - hyli2
      - hyli3
      - hyli4

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Port pour accéder à l'interface de Grafana
    environment:
      - GF_SECURITY_ALLOW_ANONYMOUS_ACCESS=true
    volumes:
      - ./observability/grafana-datasources:/etc/grafana/provisioning/datasources # Montée de volume pour la source de données
    network_mode: host
    depends_on:
      - prometheus
