node_url      = "http://localhost:4321"
rpc_port      = 8545
rest_port     = 4000
log_format    = "plain"
hyli_chain_id = 1337
eth_state_root = "0000000000000000000000000000000000000000000000000000000000000000"
bridge_cn     = "hyperlane-bridge"
hyperlane_cn  = "hyperlane"
token_cn      = "oranj"
data_directory = "data/bridge-server"
noinit        = false
